# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'messenger.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Messenger(object):
    def setupUi(self, Messenger):
        Messenger.setObjectName("Messenger")
        Messenger.resize(461, 550)
        Messenger.setStyleSheet("background-color: rgb(65, 74, 76);\n"
"background-color: rgb(10, 10, 10);\n"
"")
        self.centralwidget = QtWidgets.QWidget(Messenger)
        self.centralwidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.centralwidget.setStyleSheet("background-color: #222126")
        self.centralwidget.setObjectName("centralwidget")
        self.messagesBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.messagesBrowser.setGeometry(QtCore.QRect(10, 130, 441, 341))
        self.messagesBrowser.setStyleSheet("background-color: rgb(22, 26, 30);\n"
"color: white;\n"
"border: 1px solid #22222e;")
        self.messagesBrowser.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.messagesBrowser.setLineWidth(5)
        self.messagesBrowser.setObjectName("messagesBrowser")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-20, 0, 531, 91))
        self.frame.setStyleSheet("background-color: #22222e")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(180, 30, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(40, 10, 71, 71))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("images_messenger/logo.png"))
        self.label_2.setObjectName("label_2")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 480, 471, 61))
        self.frame_2.setStyleSheet("background-color: #22222e")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.sendButton = QtWidgets.QPushButton(self.frame_2)
        self.sendButton.setGeometry(QtCore.QRect(390, 10, 41, 41))
        self.sendButton.setStyleSheet("background-color: #22222e;\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.sendButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images_messenger/send_message.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sendButton.setIcon(icon)
        self.sendButton.setIconSize(QtCore.QSize(25, 25))
        self.sendButton.setAutoDefault(False)
        self.sendButton.setObjectName("sendButton")
        self.textInput = QtWidgets.QLineEdit(self.frame_2)
        self.textInput.setGeometry(QtCore.QRect(20, 10, 351, 41))
        self.textInput.setStyleSheet("color: white;\n"
"background-color: #22222e;\n"
"border: 2px solid gray;\n"
"border-radius: 20px;")
        self.textInput.setObjectName("textInput")
        self.nameInput = QtWidgets.QLineEdit(self.centralwidget)
        self.nameInput.setGeometry(QtCore.QRect(90, 100, 311, 21))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(8)
        self.nameInput.setFont(font)
        self.nameInput.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.nameInput.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.nameInput.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.nameInput.setAcceptDrops(True)
        self.nameInput.setToolTip("")
        self.nameInput.setStyleSheet("color: white;\n"
"background-color: #22222e;\n"
"border: 2px solid #22222e;\n"
"border-radius: 20px;")
        self.nameInput.setFrame(False)
        self.nameInput.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.nameInput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nameInput.setObjectName("nameInput")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(410, 90, 41, 41))
        self.label_3.setStyleSheet("color: white;")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("images_messenger/img2.png"))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 71, 31))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("images_messenger/img1.png"))
        self.label_4.setObjectName("label_4")
        self.frame.raise_()
        self.messagesBrowser.raise_()
        self.frame_2.raise_()
        self.nameInput.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        Messenger.setCentralWidget(self.centralwidget)

        self.retranslateUi(Messenger)
        QtCore.QMetaObject.connectSlotsByName(Messenger)

    def retranslateUi(self, Messenger):
        _translate = QtCore.QCoreApplication.translate
        Messenger.setWindowTitle(_translate("Messenger", "Messenger"))
        self.label.setText(_translate("Messenger", "Catssenger"))
        self.textInput.setPlaceholderText(_translate("Messenger", "Напишите сообщение маф..."))
        self.nameInput.setPlaceholderText(_translate("Messenger", "Введите ваше имя маф..."))
