# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'messenger.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Messenger(object):
    def setupUi(self, Messenger):
        Messenger.setObjectName("Messenger")
        Messenger.resize(390, 493)
        Messenger.setStyleSheet("background-color: rgb(65, 74, 76);\n"
                                "background-color: rgb(10, 10, 10);")
        self.centralwidget = QtWidgets.QWidget(Messenger)
        self.centralwidget.setObjectName("centralwidget")
        self.sendButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton.setGeometry(QtCore.QRect(350, 431, 30, 30))
        self.sendButton.setStyleSheet("color: rgb(255, 255, 255);\n"
                                      "background-color: rgb(41, 47, 48);")
        self.sendButton.setObjectName("sendButton")
        self.messagesBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.messagesBrowser.setGeometry(QtCore.QRect(10, 90, 371, 331))
        self.messagesBrowser.setStyleSheet("background-color: rgb(22, 26, 30);\n"
                                           "color: rgb(255, 255, 255);\n"
                                           "border-color: rgb(170, 0, 0);")
        self.messagesBrowser.setFrameShape(QtWidgets.QFrame.Panel)
        self.messagesBrowser.setLineWidth(5)
        self.messagesBrowser.setObjectName("messagesBrowser")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(0, 0, 391, 51))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(18)
        self.title.setFont(font)
        self.title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title.setAutoFillBackground(False)
        self.title.setStyleSheet("color: rgb(255, 255, 255);\n"
                                 "background-color: rgb(22, 26, 30);")
        self.title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title.setLineWidth(10)
        self.title.setTextFormat(QtCore.Qt.AutoText)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setWordWrap(False)
        self.title.setIndent(-1)
        self.title.setObjectName("title")
        self.nameInput = QtWidgets.QLineEdit(self.centralwidget)
        self.nameInput.setGeometry(QtCore.QRect(10, 60, 141, 27))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(7)
        self.nameInput.setFont(font)
        self.nameInput.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.nameInput.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.nameInput.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.nameInput.setAcceptDrops(True)
        self.nameInput.setToolTip("")
        self.nameInput.setStyleSheet("color: rgb(255, 255, 255);\n"
                                     "background-color: rgb(65, 74, 76);\n"
                                     "")
        self.nameInput.setFrame(False)
        self.nameInput.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.nameInput.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.nameInput.setObjectName("nameInput")
        self.textInput = QtWidgets.QTextEdit(self.centralwidget)
        self.textInput.setGeometry(QtCore.QRect(10, 430, 331, 31))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(7)
        self.textInput.setFont(font)
        self.textInput.setStyleSheet("color: rgb(255, 255, 255);\n"
                                     "background-color: rgb(87, 102, 105);\n"
                                     "background-color: rgb(65, 74, 76);")
        self.textInput.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textInput.setObjectName("textInput")
        Messenger.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Messenger)
        self.statusbar.setObjectName("statusbar")
        Messenger.setStatusBar(self.statusbar)

        self.retranslateUi(Messenger)
        QtCore.QMetaObject.connectSlotsByName(Messenger)

    def retranslateUi(self, Messenger):
        _translate = QtCore.QCoreApplication.translate
        Messenger.setWindowTitle(_translate("Messenger", "Messenger"))
        self.sendButton.setText(_translate("Messenger", ">"))
        self.title.setText(_translate("Messenger", "Messenger"))
        self.nameInput.setPlaceholderText(_translate("Messenger", "Введите ваше имя..."))
        self.textInput.setPlaceholderText(_translate("Messenger", "Напишете сообщение..."))
